version: "3.5"

services:
  app:
    build:
      context: ./
      dockerfile: ./build/php/Dockerfile
      target: base
    user: "${USER_ID}:${USER_ID}"
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./:/app
    environment:
      PHP_DATE_TIMEZONE: "${TIMEZONE}"

#  app2:
#    image: registry.hub.docker.com/leepeuker/movary:432434
#    user: "${USER_ID}:${USER_ID}"
#    ports:
#      - "8080:80"
#    environment:
#      PHP_DATE_TIMEZONE: "${TIMEZONE}"
#      DATABASE_HOST: "192.168.1.2"
#      DATABASE_PORT: "3308"
#      DATABASE_USER: "${DATABASE_USER}"
#      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./tmp/db/:/var/lib/mysql
      - ./tmp/:/tmp/host
    ports:
      - "${DATABASE_PORT_HOST}:3306"
