version: "3.5"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: base
    user: "${USER_ID}:${USER_ID}"
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./:/var/www/movary
    environment:
      PHP_DATE_TIMEZONE: "${TIMEZONE}"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_MYSQL_USER}
      MYSQL_PASSWORD: ${DATABASE_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_MYSQL_NAME}
    volumes:
      - movary-database:/var/lib/mysql
      - ./storage/:/tmp/host
    ports:
      - "${DATABASE_MYSQL_PORT}:3306"

volumes:
  movary-database:
