version: "3.5"

services:
  app:
    build:
      context: ./
      dockerfile: ./build/php/Dockerfile
    user: "1000:1000"
    ports:
      - "80:80"
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      WEB_DOCUMENT_ROOT: "/app/public"
      PHP_DATE_TIMEZONE: "${TIMEZONE}"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./tmp/db/:/var/lib/mysql
      - ./tmp/:/tmp/host
    ports:
      - "${DATABASE_PORT_HOST}:3306"
