version: "3.5"

services:
  app:
    build:
      context: ./
      dockerfile: ./build/Dockerfile
      target: development
      args:
        - USER_ID=${USER_ID:-1000}
    volumes:
      - ./:/app

volumes:
  movary-storage:
