version: "3.5"

services:
  app:
    build:
      context: ./
      dockerfile: ./build/php/Dockerfile
      target: development
    user: "${USER_ID}:${USER_ID}"
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./:/app
    environment:
      PHP_DATE_TIMEZONE: "${TIMEZONE}"

#  app_production:
#    build:
#      context: ./
#      dockerfile: ./build/php/Dockerfile
#      target: production
#    user: "${USER_ID}:${USER_ID}"
#    ports:
#      - "8080:80"
#    environment:
#      PHP_DATE_TIMEZONE: "${TIMEZONE}"
#      DATABASE_HOST: ""
#      DATABASE_PORT: "${DATABASE_PORT_HOST}"
#      DATABASE_USER: "${DATABASE_USER}"
#      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
#      TMDB_API_KEY: "${TMDB_API_KEY}"
#      TRAKT_USERNAME: "${TRAKT_USERNAME}"
#      TRAKT_CLIENT_ID: "${TRAKT_CLIENT_ID}"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./tmp/db/:/var/lib/mysql
      - ./tmp/:/tmp/host
    ports:
      - "${DATABASE_PORT_HOST}:3306"
