name: Bug Report
description: Report a problem
labels: ['type:bug']
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
  
      Please note that GitHub issues are exclusively for bug reports and feature requests. For support, please use our other support channels to get help.
- type: textarea
  id: description
  attributes:
    label: Description
    description: Please provide a clear and concise description of the bug or problem.
  validations:
    required: true
- type: input
  id: version
  attributes:
    label: Version
    description: What version of Movary are you running? (You can find this in Settings → App → About)
  validations:
    required: true
- type: textarea
  id: repro-steps
  attributes:
    label: Steps to Reproduce
    description: Please tell us how we can reproduce the bug.
    placeholder: |
      1. Go to [...]
      2. Click on [...]
      3. Scroll down to [...]
      4. See error in [...]
  validations:
    required: true
- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: If applicable, please provide screenshots depicting the problem.
- type: textarea
  id: logs
  attributes:
    label: Logs
    description: Please copy and paste any relevant log output. (Will be automatically formatted, no need for backticks)
    render: shell
- type: input
  id: server-os
  attributes:
    label: Server OS
    description: Provide if possible, e.g. Ubuntu 22.04, Windows 11
  validations:
    required: false
- type: dropdown
  id: client-platform
  attributes:
    label: Client Platform
    description: Provide if frontend is affected
    options:
    - Desktop
    - Smartphone
    - Tablet
- type: input
  id: device
  attributes:
    label: Client Device
    description: Provide if frontend is affected, e.g. Pixel 7a, iPhone 12, Samsung Galaxy Tab A8
- type: input
  id: client-os
  attributes:
    label: Client OS
    description: Provide if frontend is affected, e.g. Android 12, iOS 16.3, Windows 11
  validations:
    required: false
- type: input
  id: client-browser
  attributes:
    label: Client Browser
    description: Provide if frontend is affected, e.g. Firefox, Chrome, Safari, Edge
  validations:
    required: false
- type: textarea
  id: additional-context
  attributes:
    label: Additional Context
    description: Please provide any additional information that may be relevant or helpful.
