contact_links:
  - name: Support via GitHub Discussions
    url: https://github.com/leepeuker/movary/discussions
    about: Ask questions and discuss Movary with the devs and community
  - name: Support via Chat
    url: https://matrix.to/#/#movary-support:leepeuker.dev
    about: Get support via chat from the devs and community (Matrix)
  - name: General discussion Chat
    url: https://matrix.to/#/#movary-general:leepeuker.dev
    about: General open Movary discussion chat (Matrix)
