name: Deploy mkdocs

on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - mkdocs.yml
  release:
    types: [published]
    paths:
      - docs/**
      - mkdocs.yml

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: copy files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DOCS_SSH_HOST }}
          username: ${{ secrets.DOCS_SSH_USER }}
          key: ${{ secrets.DOCS_SSH_KEY }}
          source: "mkdocs.yml,docs/*"
          target: ${{ secrets.DOCS_DEPLOYMENT_DIRECTORY }}
          rm: true
