name: Run tests

on: [ pull_request ]

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build docker development image
        run: docker build --target development --tag movary ./build/

      - name: Run all test tools/suites
        run: docker run --rm -v /home/runner/work/movary/movary:/var/www/html movary composer test
